name: quiz_versiyon1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_core: ^2.31.1
  cloud_firestore: ^4.5.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hovering: ^1.0.4
  fl_chart: ^0.68.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/giris2.png
